<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Auto Peças</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
        background: url("img/veiculos.webp") no-repeat center center / cover;

            color: white;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            font-family: 'Segoe UI', sans-serif;
        }
        .container {
            background: rgba(255, 255, 255, 0.1);
            padding: 2rem;
            border-radius: 15px;
            backdrop-filter: blur(10px);
            box-shadow: 0 4px 20px rgba(0,0,0,0.3);
        }
        a.btn {
            margin: 0.5rem;
            font-weight: 600;
        }
        h1 span {
            color: #ff0707f8;
        }
    </style>
</head>

<body>
    <div class="container text-center">
        <h1>Bem-vindo à <span>Autopeças </span> 🛍️</h1>
        <p class="lead">Oque iremos fazer hoje ?</p>
        <div class="mt-4">
            <a href="?controller=user&action=login" class="btn btn-light">🔑 Login</a>
            <a href="?controller=produto&action=listar" class="btn btn-warning">📦 Produtos</a>
            <a href="?controller=venda&action=listar" class="btn btn-success">💰 Vendas</a>
            <a href="?controller=venda&action=listar" class="btn btn-success"> 📚 Nossa Historia</a>
        </div>
    </div>
</body>
</html>
