<div class="login-box">
    <div class="form-container">
        <h2>Login de Usuário</h2>
        
        <?php if (isset($_GET['erro'])): ?>
            <p class="error-message">Nome de usuário ou senha incorretos. Tente novamente.</p>
        <?php endif; ?>

        <form action="/index.php?controller=user&action=autenticar" method="POST">
            <label for="name">Nome de Usuário:</label>
            <input type="text" id="name" name="name" required>

            <label for="password">Senha:</label>
            <input type="password" id="password" name="password" required>

            <button type="submit" class="button-action">Entrar</button>
        </form>
    </div>
</div>