<h2>Login de Usuário</h2>

<?php if (isset($_GET['erro'])): ?>
    <p class="error">Nome de usuário ou senha incorretos. Tente novamente.</p>
<?php endif; ?>

<form action="/index.php?controller=user&action=autenticar" method="POST">
    <label for="name">Nome de Usuário:</label><br>
    <input type="text" id="name" name="name" required><br><br>

    <label for="password">Senha:</label><br>
    <input type="password" id="password" name="password" required><br><br>

    <button type="submit">Entrar</button>
</form>