<a href="/index.php?controller=venda&action=index" class="button-action" >Registar Nova Venda</a>

<?php if (empty($vendas)): ?>
    <p>Nenhuma venda foi registada ainda.</p>
<?php else: ?>
    <table class="styled-table">
        <thead>
            <tr>
                <th>ID da Venda</th>
                <th>Data</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($vendas as $venda): ?>
            <tr>
                <td><a href="/index.php?controller=venda&action=detalhes&id=<?php echo $venda->getId(); ?>"><?php echo htmlspecialchars($venda->getId()); ?></a></td>
                <td><a href="/index.php?controller=venda&action=detalhes&id=<?php echo $venda->getId(); ?>"><?php echo htmlspecialchars($venda->getData()->format('d/m/Y H:i')); ?></a></td>
                <td><a href="/index.php?controller=venda&action=detalhes&id=<?php echo $venda->getId(); ?>">R$ <?php echo htmlspecialchars(number_format($venda->getTotal(), 2, ',', '.')); ?></a></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>